name: Code Review with OpenAI API

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get diff on Pull Request
        id: get-diff-on-pull-request-
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo $EOF > ./diff
          git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} -- ':(exclude).github/*' >> ./diff
          echo $EOF >> ./diff
          echo "DIFF_FILES=$( printf "%q" $( cat ./diff ) )" >> $GITHUB_ENV
          echo "DIFF_BLOCK_DELIMITER=$EOF" >> $GITHUB_ENV
    
      - name: Install dependencies
        run: |
          pip install openai

      - name: Generate code review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        id: generate-review
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64 | sed "s/\///g")
          echo $EOF >> ./prompt
          echo "Could you please review the code changes? \
          You can disregard any formatting errors, as the input has been escaped. \
          Please indicate your decision by titling the first line as 'Approve' or 'Request changes'. \
          In the third line, kindly state the reason for your decision. \
          If you choose to request changes, please also provide a proposal patch.:\n \
            '${{ env.DIFF_FILES }}' \n" >> ./prompt
          echo $EOF >> ./prompt
          review=$(openai -k $OPENAI_API_KEY api completions.create -m text-davinci-003 -p "$( cat ./prompt )" --max-tokens 1024 --n 1 --stop "\n\n" --temperature 0.7)
          review_comment=$( echo $review | sed "s/$EOF.*$EOF//g" )
          echo "REVIEW=$review_comment" >> $GITHUB_ENV

      - name: Comment on pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run:
          gh pr comment -b "${{ env.REVIEW }}" "${{ env.URL }}"
